### ISSUE TITLE
Add camera Authentication

### ISSUE THREAD

**Issue by Rhantolq** [pooh-labs/eaterslab#108]

**Comment by kantoniak** [comment]
API method should check:
* if provided credentials are correct
* if authenticating key-name pair has access to this camera device

From the [generator docs](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python.md#security-feature) it seems that `ApiKey` security feature is supported in Open API 2.0. [OAS docs](https://swagger.io/docs/specification/2-0/authentication/api-keys/) shows how to define valid YAML (see "Pair of API Keys"). [drf-yasg docs](https://drf-yasg.readthedocs.io/en/stable/security.html) shows how to set it up in Django.

Headers we agreed to use were `X-DEVICE-ID` and `X-API-KEY`.

**Comment by Rhantolq** [comment]
https://www.willandskill.se/en/custom-django-admin-actions-with-an-intermediate-page/

**Comment by avan1235** [comment]
Started working on it on #160. If somebody have time can start from there

**Comment by Rhantolq** [comment]
TBC
