### ISSUE TITLE
API: Cafeteria live occupancy

### ISSUE THREAD

**Issue by Rhantolq** [pooh-labs/eaterslab#110]
* API for android to query people inside
* Database table for query caching
* Counter logic

**Comment by Rhantolq** [comment]
@avan1235 we might use your code if you have anything done yet

**Comment by avan1235** [comment]
@Rhantolq I had a draft only for model with foreign key to cafeteria and number of people inside and time stamp. I think you can rewrite this piece of code just to make sure that the whole API is consistent

**Comment by Rhantolq** [comment]
Add people_count to cafeteria, add cafeteria link to camera.
