### ISSUE TITLE
API does not check credentials when creating camera events

### ISSUE THREAD

**Issue by kantoniak** [pooh-labs/eaterslab#128]
I was able to create camera events without any authorization. API method should check:
* if provided credentials are correct
* if authenticating key-name pair has access to this camera device

From the [generator docs](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python.md#security-feature) it seems that `ApiKey` security feature is supported in Open API 2.0. [OAS docs](https://swagger.io/docs/specification/2-0/authentication/api-keys/) shows how to define valid YAML (see "Pair of API Keys"). [drf-yasg docs](https://drf-yasg.readthedocs.io/en/stable/security.html) shows how to set it up in Django.

Headers we agreed to use were `X-DEVICE-ID` and `X-API-KEY`.

**Comment by kantoniak** [comment]
I think #81 is relevant here, but it may have been implemented already.

**Comment by Rhantolq** [comment]
This will close #108

**Comment by kantoniak** [comment]
Oops, I'm closing this one as duplicate of #108. Description moved to comments in mentioned issue.
