### ISSUE TITLE
Occupancy statistics include events outside range

### ISSUE THREAD

**Issue by kantoniak** [pooh-labs/eaterslab#163]
Reproduction:
1. Create cafeteria and camera
2. Create `OCCUPANCY_OVERRIDE` event for this camera (with date e.g. 2020-05-30)
3. Call occupancy API (note that time range is before the event): `api/beta/cafeterias/1/stats/occupancy?start_timestamp=2020-04-19T22:00:00.000Z&end_timestamp=2020-05-02T22:00:00.000Z`
4. Last entry contains override value:
```
[
  // ...
  {
      "id":313,
      "timestamp":"2020-05-03T01:00:00+02:00",
      "occupancy":5,
      "occupancy_relative":0.5 
  }
]

**Comment by avan1235** [comment]
@kantoniak I don't understand the problem. Please write a PM to me or explain it wider here.

**Comment by avan1235** [comment]
Closing for now. if something similar noticed in the feature then open new issue for this
