### ISSUE TITLE
Heroku: set up cronjobs

### ISSUE THREAD

**Issue by kantoniak** [pooh-labs/eaterslab#175]
We will need to run two cronjobs on the server:
* disconnecting cameras
* resetting demo data.
Additionaly, demo data should reset every time we push to prod server (dev too?).

### Disconnecting cameras
Should ideally run every 3 minutes if Heroku allows it.
```
python manage.py update_disconnected_cameras
```

### Demo data reset
Should happen in reasonable intervals, np. at 2 AM every day. Blocked on #172 right now.
```
# DROP and CREATE database or public schema first
python manage.py migrate
python manage.py loaddata fixtures/demo-data.yaml
python manage.py reset_passwords  # Set password equal to username for each user
python manage.py generate_events  # Use --from/to=YYYY-MM-DD to select dates
python manage.py generate_reviews  # Use --from/to=YYYY-MM-DD to select dates
```

### Things to do in this issue
1. Investigate how to run cronjobs on Heroku.
1. Create two bash scripts for jobs.
1. Setup Heroku cronjob.
1. Modify Heroku workflows to run demo setup.

**Comment by avan1235** [comment]
Setup done similarly as the standard cron jobs on heroku environment running 
```bash
psql $DATABASE_URL -t -c "select 'drop table \"' || tablename || '\" cascade;' from pg_tables where schemaname = 'public'" | psql $DATABASE_URL && python manage.py migrate && python manage.py loaddata fixtures/demo-data.yaml && python manage.py reset_passwords  && python manage.py generate_events && python manage.py generate_reviews 
```

**Comment by avan1235** [comment]
@kantoniak do you think we can close this for now? 
(the jobs are set up at 3:00AM UTC) so we should see first result tomorrow

**Comment by avan1235** [comment]
Additionally for me this not need extra documentation as you already included all these commands in [doc](https://github.com/pooh-labs/eaterslab/tree/master/django-server#sample-data)

**Comment by kantoniak** [comment]
Could you describe this setup in some document? Is _Project plan/Technical processes/Infrastructure_ a good place?

I tried to do some googling and found these websites:
https://devcenter.heroku.com/articles/scheduler
https://devcenter.heroku.com/articles/free-dyno-hours
Are we using any of it?
