### ISSUE TITLE
Stats in web panel - cannot choose canteen

### ISSUE THREAD

**Issue by avan1235** [pooh-labs/eaterslab#198]
Using the [admin panel](https://eaterslab.herokuapp.com/admin/stats/) to see stats data user cannot choose the wanted canteen. I think it may be caused by the changes in api but needs investigation. (of course after Friday xd)

**Comment by kantoniak** [comment]
Reproduction:
1. Load sample data
2. Log in as `admin`
3. Open statistics panel. There are no cafeterias in the list

Please add reproduction next time. If bug was more complicated I would not know what to fix.

**Comment by kantoniak** [comment]
You can use any owner account (`owner-1` or `owner-2`) as a workaround for now.
