### ISSUE TITLE
Modify stats to return max value from interval

### ISSUE THREAD

**Issue by kantoniak** [pooh-labs/eaterslab#203]
Right now, statistics compute number of people who entered and left and adds this change to previous timestamp value. As a result, people who entered and left in the same interval are not counted.

1. Modify occupancy calculation:
    * For each interval script should take maximum occupancy as a value
    * Interval should generate timestamp in its middle (for example, with grouping by hour, for interval `2020-06-07 13:00:00`-`2020-06-07 14:00:00` timestamp should be `2020-06-07 13:30:00`)
2. Modify average reviews:
    * Move interval timestamps from beginning of the interval to its middle (same as in occupancy)

**Comment by avan1235** [comment]
Can take this. Will do this until tomorrow.

**Comment by avan1235** [comment]
@kantoniak The max value doesn't have to be the best choice as I think now. What about the weigthened average by the intervals of people being inside or something similar?

**Comment by kantoniak** [comment]
Whatever works in statistics, but I still have a feeling max would work best.
