### ISSUE TITLE
Set up charting library for web app

### ISSUE THREAD

**Issue by kantoniak** [pooh-labs/eaterslab#23]
Web app will need a JS charting library for displaying analytics.

**Comment by kantoniak** [comment]
D3.js:
- Powerful yet complex
- Nice animations
- It will be easier to support WCAG if we want to

Chart.js
- Simpler
- Has animations too, but I'm not sure if we can animate adding points

**Comment by avan1235** [comment]
Just keep in mind maybe to get it in the materia design style in order to get beatifully designe system

**Comment by kantoniak** [comment]
[Plottable.js](http://plottablejs.org/components/):
* Build on top of D3.js
* Contains pre-made char components
* Supports plotting multiple datasets (useful for our correlation analysis)
* Built-in interaction handlers if we need them
