### ISSUE TITLE
HTTPS support for API

### ISSUE THREAD

**Issue by kantoniak** [pooh-labs/eaterslab#61]
Currently API does not support secure HTTPS, what exposes all communications between mobile clients and camera devices. We need to enable TLS for DRF.

**Comment by avan1235** [comment]
@kantoniak  Let's see at https://eaterslab.herokuapp.com. It's working now, not sure if it was not working before but now I verified account on heroku with credit card and its just working. Also https://www.sslshopper.com/ssl-checker.html#hostname=https://eaterslab.herokuapp.com gives us some confirmation about tls presence

**Comment by kantoniak** [comment]
Can you make a test api call over HTTPS to confirm it works from a client? If so, we're good.

**Comment by kantoniak** [comment]
All clients should use HTTPS by default anyway 😉

**Comment by kantoniak** [comment]
Closed by #71.
